// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  Contatti: 'Contacts',
  'INGEGNERIA CIVILE, AMBIENTALE E TERRITORIALE': 'CIVIL, ENVIRONMENTAL AND TERRITORIAL ENGINEERING',
  'INGEGNERIA INDUSTRIALE E DELL\' INFORMAZIONE': 'INDUSTRIAL AND INFORMATION ENGINEERING',
  'MODA, INTERNI, COMUNICAZIONE, PRODOTTO': 'FASHION, INTERIORS, COMMUNICATION, PRODUCT',
  'Questo sito non è affiliato al Politecnico di Milano': 'This site is not affiliated with the Politecnico di Milano',
  'Scuola 3I': 'School 3I',
  'Scuola AUIC': 'AUIC school',
  'Scuola Design': 'School Design',
  'Scuola ICAT': 'ICAT school',
  'Consigli acquisto PC': 'PC buying advice',
  'Scegli la tua scuola:': 'Choose your school:',
  'ARCHITETTURA URBANISTICA INGEGNERIA DELLE COSTRUZIONI': 'URBAN ARCHITECTURE CONSTRUCTION ENGINEERING', // UNUSED
  'Tutti i nostri contatti e le nostre pagine social si trovano facilmente sul nostro': 'All our contacts and our social pages can be easily found on ours',
  'sito web principale': 'main website'
}
