// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  Contatti: 'Contatti',
  'INGEGNERIA CIVILE, AMBIENTALE E TERRITORIALE': 'INGEGNERIA CIVILE, AMBIENTALE E TERRITORIALE',
  'INGEGNERIA INDUSTRIALE E DELL\' INFORMAZIONE': 'INGEGNERIA INDUSTRIALE E DELL\' INFORMAZIONE',
  'MODA, INTERNI, COMUNICAZIONE, PRODOTTO': 'MODA, INTERNI, COMUNICAZIONE, PRODOTTO',
  'Questo sito non è affiliato al Politecnico di Milano': 'Questo sito non è affiliato al Politecnico di Milano',
  'Scuola 3I': 'Scuola 3I',
  'Scuola AUIC': 'Scuola AUIC',
  'Scuola Design': 'Scuola Design',
  'Scuola ICAT': 'Scuola ICAT',
  'Consigli acquisto PC': 'Consigli acquisto PC',
  'Scegli la tua scuola:': 'Scegli la tua scuola:'
}
